name: 'Deploy Hello World (RG)'
 
on:
  workflow_dispatch:
 
jobs:
  cd:
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_CLI_ARGS_apply: "-auto-approve -parallelism=30"
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      # Hello world
      - name: Terraform Init
        id: init
        run: terraform init -no-color
        working-directory: helloworld
      - name: Terraform Apply
        id: apply
        if: ${{ success() }}
        run: terraform apply
        working-directory: helloworld
